//Member
//Create a member
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test@test.ch",
  "firstname": "test",
  "lastname": "test",
  "password": "test123"
}

###

//Get Token from Member
POST http://localhost:8080/api/games
Content-Type: application/json

{
  "memberrank": {
    "test": "FIRST",
    "test2": "SECOND",
    "test3": "THIRD",
    "test4": "LAST"
  },
  "startdate": "test",
  "enddate": "test123"
}
###

//Add Game
POST http://localhost:8080/api/games

//Get User Games